apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qryn-all-in-one.fullname" . }}-qryn
  labels:
    k8slens-edit-resource-version: v1
  {{- include "qryn-all-in-one.labels" . | nindent 4 }}
data:
  {{- .Values.qryn | toYaml | nindent 2}}
